from pyspark.sql.types import (
    StructType, StructField,
    StringType, BooleanType, IntegerType
)

# Define your DataFrame schema once, here
DF_SCHEMA = StructType([
        StructField("_id", StringType(), nullable=True),
        StructField("time_stamp", StringType(), nullable=True),
        StructField("ip", StringType(), nullable=True),
        StructField("user_agent", StringType(), nullable=True),
        StructField("resolution", StringType(), nullable=True),
        StructField("user_id_db", StringType(), nullable=True),
        StructField("device_id", StringType(), nullable=True),
        StructField("api_version", StringType(), nullable=True),
        StructField("store_id", StringType(), nullable=True),
        StructField("local_time", StringType(), nullable=True),
        StructField("show_recommendation", BooleanType(), nullable=True),
        StructField("current_url", StringType(), nullable=True),
        StructField("referrer_url", StringType(), nullable=True),
        StructField("email_address", StringType(), nullable=True),
        StructField("recommendation", BooleanType(), nullable=True),
        StructField("utm_source", StringType(), nullable=True),
        StructField("collection", StringType(), nullable=True),
        StructField("product_id", StringType(), nullable=True),
        StructField("viewing_product_id", StringType(), nullable=True),
        StructField("cat_id", StringType(), nullable=True),
        StructField("collect_id", StringType(), nullable=True),
        StructField("option", StringType(), nullable=True),
        StructField("order_id", StringType(), nullable=True),
        StructField("recommendation_product_id", StringType(), nullable=True),
        StructField("recommendation_clicked_position", StringType(), nullable=True),
        StructField("utm_medium", StringType(), nullable=True),
        StructField("key_search", StringType(), nullable=True),
        StructField("price", StringType(), nullable=True),
        StructField("currency", StringType(), nullable=True),
        StructField("recommendation_product_position", IntegerType(), nullable=True),
        StructField("is_paypal", BooleanType(), nullable=True),
        StructField("cart_products", StringType(), nullable=True),
    ])
